name: Shardeum Node CI

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: ${{ vars.NODE_VERSION }}
        type: string
      lint-required:
        required: false
        default: ${{ vars.IS_LINT_REQUIRED }}
        type: boolean
      format-check-required:
        required: false
        default: ${{ vars.IS_FORMAT_CHECK_REQUIRED }}
        type: boolean
      apply-patches-required:
        required: false
        default: ${{ vars.IS_APPLY_PATCHES_REQUIRED }}
        type: boolean
      unit-tests-required:
        required: false
        default: ${{ vars.IS_UNIT_TESTS_REQUIRED }}
        type: boolean
  workflow_dispatch:
    inputs:
      node-version:
        required: false
        default: ${{ vars.NODE_VERSION }}
        type: string
      lint-required:
        required: false
        default: ${{ vars.IS_LINT_REQUIRED }}
        type: boolean
      format-check-required:
        required: false
        default: ${{ vars.IS_FORMAT_CHECK_REQUIRED }}
        type: boolean
      apply-patches-required:
        required: false
        default: ${{ vars.IS_APPLY_PATCHES_REQUIRED }}
        type: boolean
      unit-tests-required:
        required: false
        default: ${{ vars.IS_UNIT_TESTS_REQUIRED }}
        type: boolean
jobs:
  merge-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ github.event.inputs['node-version'] }}

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --ignore-scripts
          echo "Dependency installation complete."
        continue-on-error: false

      - name: Lint
        id: lint
        run: |
          echo "Running Linter..."
          npm run lint
          echo "Running Linter complete."
        continue-on-error: true

      - name: Format check
        id: format_check
        run: |
          echo "Running format check..."
          npm run format-check
          echo "Format check complete."
        continue-on-error: true

      - name: Test apply patches
        id: test_apply_patches
        run: |
          set -e
          shopt -s nullglob
          patches=(*.patch)
          if [ ${#patches[@]} -eq 0 ]; then
            echo "No patches to test."
          else
            for patch in "${patches[@]}"; do
              echo "Testing $patch"
              git apply --check -v "$patch" || (echo "Failed to apply patch: $patch" && exit 1)
            done
            echo "All patches applied successfully."
          fi
        continue-on-error: true

      - name: Build
        id: build
        run: |
          echo "Building the code..."
          npm run build
          echo "Build complete."
        continue-on-error: false

      - name: Unit Tests
        id: unit_tests
        run: |
          echo "Running Unit Tests..."
          npm test
          echo "Unit Tests complete."
        continue-on-error: true

      - name: Check if any step failed
        id: check_failure
        run: |
          failed=false

          # Check Lint
          if [[ "${{ steps.lint.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'lint' has failed! Please expand lint step output for more details."
            if ${{ inputs.lint-required }}; then
              failed=true
            fi
          fi

          # Check Format Check
          if [[ "${{ steps.format_check.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'format_check' has failed! Please expand format_check step output for more details."
            if ${{ inputs.format-check-required }}; then
              failed=true
            fi
          fi

          # Check Apply Patches
          if [[ "${{ steps.test_apply_patches.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'test_apply_patches' has failed! Please expand test_apply_patches step output for more details."
            if ${{ inputs.apply-patches-required }}; then
              failed=true
            fi
          fi

          # Check Unit Tests
          if [[ "${{ steps.unit_tests.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'unit_tests' has failed! Please expand unit_tests step output for more details."
            if ${{ inputs.unit-tests-required }}; then
              failed=true
            fi
          fi

          if [ "$failed" == "true" ]; then
            exit 1
          fi
