name: Shardeum Reusable CI Workflow for Node projects

on:
  issue_comment:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: "18.16.1"
        type: string
      lint-required:
        required: false
        default: true
        type: boolean
      format-check-required:
        required: false
        default: true
        type: boolean
      apply-patches-required:
        required: false
        default: true
        type: boolean
      unit-tests-required:
        required: false
        default: true
        type: boolean
      jenkins-qa-required:
        required: false
        default: true
        type: boolean

jobs:
  debug-info:
    name: Display useful debugging information
    steps:
      - name: Display Event details
        run: |
          echo "Event Name:           ${{ github.event_name }}"
          echo "Event Action:         ${{ github.event.action }}"
          echo "Event Sender Type:    ${{ github.event.sender.type }}"
  pr-agent:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.type != 'Bot' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "true" # enable auto review
          github_action_config.auto_describe: "false" # disable auto describe
          github_action_config.auto_improve: "false" # disable auto improve
        continue-on-error: true

  merge-checks:
    runs-on: ubuntu-latest
    if: github.event_name != 'issue_comment'
    env:
      NODE_VERSION: ${{ inputs.node-version || vars.NODE_VERSION }}
      IS_LINT_REQUIRED: ${{ inputs.lint-required || vars.IS_LINT_REQUIRED }}
      IS_FORMAT_CHECK_REQUIRED: ${{ inputs.format-check-required || vars.IS_FORMAT_CHECK_REQUIRED }}
      IS_APPLY_PATCHES_REQUIRED: ${{ inputs.apply-patches-required || vars.IS_APPLY_PATCHES_REQUIRED }}
      IS_UNIT_TESTS_REQUIRED: ${{ inputs.unit-tests-required || vars.IS_UNIT_TESTS_REQUIRED }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Echo Input Values and Check Defaults
        run: |
          echo "Node Version:           ${{ env.NODE_VERSION }}"
          echo "Lint Required:          ${{ env.IS_LINT_REQUIRED }}"
          echo "Format Check Required:  ${{ env.IS_FORMAT_CHECK_REQUIRED }}"
          echo "Apply Patches Required: ${{ env.IS_APPLY_PATCHES_REQUIRED }}"
          echo "Unit Tests Required:    ${{ env.IS_UNIT_TESTS_REQUIRED }}"
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --ignore-scripts
          echo "Dependency installation complete."
        continue-on-error: false

      - name: Lint
        id: lint
        run: |
          echo "Running Linter..."
          npm run lint
          echo "Running Linter complete."
        continue-on-error: true

      - name: Format check
        id: format_check
        run: |
          echo "Running format check..."
          npm run format-check
          echo "Format check complete."
        continue-on-error: true

      - name: Test apply patches
        id: test_apply_patches
        run: |
          set -e
          shopt -s nullglob
          patches=(*.patch)
          if [ ${#patches[@]} -eq 0 ]; then
            echo "No patches to test."
          else
            for patch in "${patches[@]}"; do
              echo "Testing $patch"
              git apply --check -v "$patch" || (echo "Failed to apply patch: $patch" && exit 1)
            done
            echo "All patches applied successfully."
          fi
        continue-on-error: true

      - name: Build
        id: build
        run: |
          echo "Building the code..."
          npm run build
          echo "Build complete."
        continue-on-error: false

      - name: Unit Tests
        id: unit_tests
        run: |
          echo "Running Unit Tests..."
          npm test
          echo "Unit Tests complete."
        continue-on-error: true

      - name: Check if any step failed
        id: check_failure
        run: |
          failed=false
          
          # Check Lint
          if [[ "${{ steps.lint.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'lint' has failed! Please expand the step output for more details."
            if ${{ env.IS_LINT_REQUIRED }}; then
              failed=true
            fi
          fi
          
          # Check Format Check
          if [[ "${{ steps.format_check.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'format_check' has failed!"
            if ${{ env.IS_FORMAT_CHECK_REQUIRED }}; then
              failed=true
            fi
          fi
          
          # Check Apply Patches
          if [[ "${{ steps.test_apply_patches.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'test_apply_patches' has failed!"
            if ${{ env.IS_APPLY_PATCHES_REQUIRED }}; then
              failed=true
            fi
          fi
          
          # Check Unit Tests
          if [[ "${{ steps.unit_tests.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'unit_tests' has failed!"
            if ${{ env.IS_UNIT_TESTS_REQUIRED }}; then
              failed=true
            fi
          fi
          
          if [ "$failed" == "true" ]; then
            echo "Please expand the failed step(s) for more details."
            exit 1
          fi

  trigger-jenkins-job:
    if: ${{ vars.JENKINS_QA_JOB }} != '' && ${{ github.event_name }} != 'issue_comment'
    needs: merge-checks
    runs-on: ubuntu-latest
    env:
      IS_JENKINS_QA_REQUIRED: ${{ inputs.jenkins-qa-required || vars.IS_JENKINS_QA_REQUIRED }}
    steps:
      - name: Echo Input Values and Check Defaults
        run: |
          echo "Jenkins job Required:           ${{ env.IS_JENKINS_QA_REQUIRED }}"
      - name: Set Branch Name
        id: vars
        run: |
          # Determine the branch name
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          
          # Determine the repository name, prioritize the secret if it exists
          if [ -n "${{ vars.REPO_NAME }}" ]; then
            REPO_NAME=${{ vars.REPO_NAME }}
          else
            REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          fi
          
          # Capitalize the repository name
          REPO_NAME_CAPITALIZED=$(echo "${REPO_NAME:0:1}" | tr '[:lower:]' '[:upper:]')${REPO_NAME:1}
          
          # Export the environment variables
          echo "REPO_NAME=${REPO_NAME_CAPITALIZED}" >> $GITHUB_ENV

      - name: Trigger Jenkins QA Job
        id: trigger_jenkins_qa_job
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          REPO_NAME: ${{ env.REPO_NAME }}
          JENKINS_URL: ${{ vars.JENKINS_URL }}
        run: |
          curl -f -X POST "${JENKINS_URL}/job/${{ vars.JENKINS_QA_JOB }}/buildWithParameters?SPECIFY_${REPO_NAME}_BRANCH=true&${REPO_NAME}_BRANCH=${BRANCH_NAME}" \
            --user "${{ secrets.JENKINS_API_CREDS }}"
        continue-on-error: true

      - name: Check if any step failed
        id: check_failure
        run: |
          failed=false
          
          # Check Jenkins QA job - This just checks that the workflow step passes but will later be configured to wait for the actual Jenkins job to pass/fail
          if [[ "${{ steps.trigger_jenkins_qa_job.outcome }}" == "failure" ]]; then
            echo "ERROR! Step 'Trigger Jenkins QA Job' has failed!"
            if ${{ env.IS_JENKINS_QA_REQUIRED }}; then
              failed=true
            fi
          fi
          if [ "$failed" == "true" ]; then
            echo "Please expand the failed step(s) for more details."
            exit 1
          fi