name: Summarize

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
    secrets:
      github-token:
        required: true

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Download logs artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.job_name }}-logs

      - name: List artifact contents
        run: ls -lR  # List all files and directories recursively

      - name: Summarize logs and post comment
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          LOGS=$(cat *.txt)
          PROMPT="Summarize the following GitHub workflow logs:\r$LOGS"

          JSON_PAYLOAD=$(jq -n --arg text "$PROMPT" '{"contents":[{"parts":[{"text":$text}]}]}')


          # Call Gemini API using curl
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${GEMINI_API_KEY}")

          # Check if curl command was successful
          if [ $? -ne 0 ]; then
            echo "Error: Failed to call Gemini API."
            exit 1
          fi

          # Extract summary from Gemini response using jq
          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')

           # Validate SUMMARY
          if [ -z "$SUMMARY" ] || [ "$SUMMARY" == "null" ]; then
            echo "Error: Summary is empty or null."
            exit 1
          fi


          # Set the summary as an environment variable for the next step
          echo "SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post PR comment OR Log summary
        # Use a conditional step to either post a comment or log the summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.SUMMARY }}' 
            });
        env:
          SUMMARY: ${{ env.SUMMARY }}

      - name: Log summary (if not a pull request)
        # This step will run if it's NOT a pull request
        if: github.event_name != 'pull_request'
        run: 'echo "Workflow summary: ${{ env.SUMMARY }}" >> workflow_summary.log'
